### ISSUE TITLE
Notification preview pops up twice

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#236]
When changing the position of the notification messages in lxqt-config-notificationd 
for some seconds the preview pops first up at the previous position.

##### Expected Behavior

Preview notification pops up in selected position of the screen.

##### Current Behavior

Pops up twice, as described.

##### Possible Solution

Inserting a delay until new setting is applied?

 

* Distribution & Version: Arch + latest git checkout, but is also present in official arch packages
* Qt Version: 5.9.1-3

**Comment by stefonarch** [comment]
It' still here.

**Comment by tsujan** [comment]
At first I thought it was a feature (although useless) but, after looking at the code, I saw that it wasn't intentional. Will fix it.

**Comment by tsujan** [comment]
Didn't find a way.

We send the notification after changing the position but it takes a short time before the change is written to the config file and the app sees it. I found no reliable interval for waiting; neither the signal `LXQt::Settings::settingsChangedByApp()` nor the method `QSettings::sync()` guarantees a good timing. Waiting for an arbitrary time is not a solution either because the file may be on SSD or HDD (fast or slow).

**Comment by stefonarch** [comment]
It's not a big issue, users will change it once if ever.

I noticed that the preview includes the position ("bottom-right" ecc) in the test message not translated.
I made some trial with out success, not sure if those  positions can be translated, but IMO +align could be just removed, no need to tell that bottom right is where it is.
https://github.com/lxqt/lxqt-notificationd/blob/3a3d0080c1ecaa93745add5a120f7e3d21b53a64/config/basicsettings.cpp#L128

`    LXQt::Notification::notify(tr("Notification demo ") + align,`

**Comment by tsujan** [comment]
> not sure if those positions can be translated

They can, by adding eight conditions immediately above `LXQt::Notification::notify`. I think it's better to add them because the notification starts at the previous position.

**Comment by tsujan** [comment]
OK. You could make a new translatable string by using the conditions that already exist. There's no need to additional conditions; sorry. I just meant that `align` shouldn't be changed.

I don't think we need the dash in the translatable string (e.g., `tr("top left)` is good).

**Comment by stefonarch** [comment]
I see it's above my skills, it [doesn't work](https://github.com/lxqt/lxqt-notificationd/compare/master...stefonarch:add_translations?expand=1).

**Comment by tsujan** [comment]
> I see it's above my skills

The area of your skills will be widened. I hope it'll overlap mine soon.

After `QString align;`, you could add
```c++
QString str;
```
Then, you could define `str` under each condition. For example, the first condition can be changed to:
```c++
    if (topLeftRB->isChecked())
    {
        align = QL1S("top-left");
        str = tr("top left");
    }
```
And the same for the other conditions. At last, you put `str` in `LXQt::Notification::notify(...` instead of `align`. (Hopefully, I haven't made a mistake; test it.)

**Comment by stefonarch** [comment]
I can say I tried, but it still doesn't work, at least it compiles ;)
https://github.com/lxqt/lxqt-notificationd/compare/master...stefonarch:add_translations?expand=1

**Comment by stefonarch** [comment]
Talking about the issue here: how about adding a "Preview" button? 
The time between choosing the position and clicking this button could be always enough no?

**Comment by tsujan** [comment]
It seems correct to me. You don't have any translation installed yet. If you see "bottom right", and not "bottom-right", in the notification, that shows it works.

**Comment by tsujan** [comment]
> Talking about the issue here: how about adding a "Preview" button?

It'll make no difference. If the user clicks it immediately after changing the position, the notification will start at the previous position.

**Comment by tsujan** [comment]
I tested you changes and they had no problem. Just a suggestion:

Now, we see "Notification demo top right", for example. It's a little weird — actually, it was weird before. So, we can change "Notification demo " to ""Notification demo at " (there's a space at the end), so that it becomes "Notification demo at top right".

**Comment by stefonarch** [comment]
Sure I tested with translations, ran lxqt-transupdate, did some translation and recompiled - they weren't displayed.
But as I suggested before: for  me not to include the position at all is better, because it appears first also on the wrong place:
```
Notification demo

This is a test notification.
All notifications will now appear here on LXQt.
``` 

is clear.

**Comment by tsujan** [comment]
> looks like overnight it started working showing translations

Yes, the patch is correct. Please make a PR.

**Comment by tsujan** [comment]
Oh, you'd made the PR.

Af for a "Preview" button instead of automatic showing, now I think it's better because most users won't click it immediately. At least, starting at the previous position will be less likely with it. Will make a PR later.

**Comment by stefonarch** [comment]
> Af for a "Preview" button instead of automatic showing, now I think it's better because most users won't click it immediately. At least, starting at the previous position will be less likely with it. Will make a PR later.

My thought. We can test it. Here with an sdd it's maybe half a second, a small delay in the button action maybe?

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/lxqt-notificationd/pull/293
