### ISSUE TITLE
[Feature request] Add "Do not disturb" mode

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#270]
Sometimes it could be useful to postpone all notifications (work, movie ecc) for an amount of time (like ½h, 1h, 2h)
It could also be triggered somehow  by "pause idleness watcher" with fullscreen or when https://github.com/lxqt/lxqt-powermanagement/pull/260 is implemented. adding an checkbox "pause also notification".

 
##### Possible Solution

* Allow 0 seconds (related https://github.com/lxqt/lxqt-notificationd/issues/211) for timeout
* toggle configuration from actual settings to `0 seconds` and `Save last 10`
*  at the end show unattended notifications
 
 (follow up of https://github.com/lxqt/lxqt-panel/issues/1320)

**Comment by jmfernandez** [comment]
Yes, it would be very useful in this "teleconferences" world, in order to avoid showing any notification for half an our or one hour, for instance, in order to avoid them when screen is being shared, video or slideshow is in progress.

**Comment by stefonarch** [comment]
At the moment this can be achieved by stopping the  notification module in "Session Settings", but there will be no "missed" notifications when reactivating.

**Comment by jmfernandez** [comment]
> At the moment this can be achieved by stopping the notification module in "Session Settings", but there will be no "missed" notifications when reactivating.

An additional drawback is that it will not be automatically re-enable after a timeout.

**Comment by tsujan** [comment]
There's a design problem that should be solved before adding codes for the new mode:

We show the tray icon *only when* there are unattended notifications. So, unlike in power management, we can't add a pause menu there. On the other hand, if we always show the tray icon, it'll lose its usefulness as a reminder that there are unattended notifications.

Adding a pause setting in the notifications config dialog isn't the solution because it's hidden from the user.

Using the tray icon of power management for this is impossible. Even if it was possible, we shouldn't do it because notifications aren't related to power management — so say nothing of computers without battery.

Showing the icon permanently and using another icon when there are unattended notifications would be a solution if there was a good icon for the latter in all icon sets, but that's not the case. Should we add our own icon?

**Comment by tsujan** [comment]
A simple solution — as far as designing is concerned — is forgetting about pause, adding a permanent setting for the new mode to the config dialog and showing a startup notification about it, as KDE does.

**Comment by stefonarch** [comment]
I didn't quite understand the latter.

A possibility could be "Don't show notification popups" setting, and thenalways show the icon, with a counter. 
So this would not disturb.

**Comment by tsujan** [comment]
> ... and then always show the icon, with a counter.

The existence of the icon informs the user about the existence of unattended notifications by a glance. I think we shouldn't sacrifice this important functionality.

**Comment by stefonarch** [comment]
I've in mind to have all  somehow:

* Behavior as it is now: icon only pops up when there are unattended notifications
* Always shows icon with unattended notifications,
* Toggle popups (do not disturb). This is hard to activate when no icon is present, needs to be done in settings.
*  Showing number of last unattended notifications.

I don't use the unattended notifications, as I hardly click away any notification - I just read it on the fly and let it expire, and doing so it will end up as "not seen".

**Comment by tsujan** [comment]
> Always shows icon with unattended notifications,

This is the same as "Behavior as it is now:.."; isn't it?

> Toggle popups (do not disturb). This is hard to activate when no icon is present, needs to be done in settings.

We can add an option for the "do-not-disturb" mode to settings dialog. But what if the user forgets about it? I mean how do we remind he/she that he'll see no notification because he's activated the do-not-disturb mode?

Some people don't like it when I say the do-not-disturb mode is at odds with the concept of notification. OK, we might add it but we should also make sure that the user won't forget about it. The question is "How?".

> Showing number of last unattended notifications.

Why? What's the use of showing the number? If there are unattended notifications, there will be a tray icon and the user could click it and see the list. If there's no untended notification, there will be no tray icon.

**Comment by tsujan** [comment]
> but we should also make sure that the user won't forget about it

Is the following answer to my above question acceptable to you?

When "do-not-disturb" mode is activated, treat "all notifications* as unattended (because they aren't shown) and add an appropriate emblem to the tray icon, accompanied by an appropriate tooltip.

**Comment by stefonarch** [comment]
> > Always shows icon with unattended notifications,
> 
> This is the same as "Behavior as it is now:.."; isn't it?

No, as it disappears when they are cleaned. This would be useful to toggle "do not disturb".



> Is the following answer to my above question acceptable to you?
> 
> When "do-not-disturb" mode is activated, treat _all notifications_ as unattended (because they aren't shown) and add an appropriate emblem to the tray icon, accompanied by an appropriate tooltip.

The downside is that is has to be activated in settings, right? 
Could be undone automatically with "clear all & stop "do not disturb mode".

**Comment by tsujan** [comment]
> No, as it disappears when they are cleared.

The tray icon already disappears when the list is cleared.

> The downside is that is has to be activated in settings

IMHO, it isn't a downside because the user can't ignore that he has activated the mode as soon as the first notification is triggered (silently) — because of the emblem. Moreover, the tray menu already has an item for opening the config dialog.

There will be several important details that should be considered in the code. The implementation won't be easy but is doable in a clean way.

**Comment by tsujan** [comment]
The emblem can be like this, with a semi-transparent background for it to bee seen with all icons:

![emblem](https://user-images.githubusercontent.com/981076/128048862-daf4ee1c-1ec8-4067-a287-befeec5cba8c.png)

**Comment by stefonarch** [comment]
Looks fine!
In the icon menu an item  "exit do not disturb" "show notifications" or similar?

**Comment by stefonarch** [comment]
As mentioned here https://github.com/lxqt/lxqt/discussions/2054#discussioncomment-1135839 to be sure I switched back to the master branch, and telegram icon is back....

**Comment by stefonarch** [comment]
Note: I didn't saw this happen with the first commit.

**Comment by tsujan** [comment]
> Note: I didn't saw this happen with the first commit.

I assure you that Telegram's icon doesn't have the slightest relation to this patch. But it makes me worry about Status Notifier (see my previous comment).

**Comment by tsujan** [comment]
@stefonarch 
If you ran Telegram after installing it, the generic icon is quite possible. See https://github.com/lxqt/libqtxdg/issues/226. In that case,  restarting the panel will restore the correct icon once for all.

**Comment by stefonarch** [comment]
Sure I restarted telegram, panel, session and even laptop - always generic icon with telegram

**Comment by tsujan** [comment]
If it persists, please open an issue at panel's bug tracker. Here isn't a good place.

**Comment by stefonarch** [comment]
Sure I restarted everything, from panel to session to laptop.
Recompiled panel now (although I saw only  new translations) and reinstalled the "do not disturb" *.deb package, and it didn't happen again. So for the moment all good but there is something sleeping with those generic icons.

**Comment by tsujan** [comment]
> but there is something sleeping with those generic icons.

It may be just https://github.com/lxqt/libqtxdg/issues/226 but, since you said you restarted panel, there may be more.

> by the way: maybe the volume change notifications should be always shown

"Don't disturb" is what it means ;) Frankly, I won't use it because, IMO, it's at odds with notification but if a user is disturbed by notifications, there's an option now. IMO, having another exception list for the do-not-disturb mode would be weird, if not an overkill.

**Comment by stefonarch** [comment]
I didn't think of another option, but volume change isn't actually a notification coming from elsewhere but an action feedback, triggered by the  user.
I see now that libqtxdg had an update  `750380b..dcac08a` so not all was up-to date with git master.

**Comment by tsujan** [comment]
> but volume change isn't actually a notification coming from elsewhere

There's no distinction in the code. Volume change comes from Panel, while `lxqt-notificationd` doesn't depend on lxqt-panel. Moreover, some users might complain rightly ("It was supposed not to disturb...").

**Comment by stefonarch** [comment]
Today after clearing the notifications at the next notificationsI got  again the generic icon, clearing them and doing  an `notify-send test -t 10` icon was ok. 
System was only suspended and all relevant components _should_ be up-to-date, will check later.

**Comment by tsujan** [comment]
Do you have https://github.com/lxqt/lxqt-notificationd/pull/271/commits/d31eb110414d8a8770837d29b00624ed41166a93 too?

**Comment by stefonarch** [comment]
Yes.

**Comment by tsujan** [comment]
> Yes.

Since you've seen the same thing with Telegram a few times and because Telegram also adds emblems to its tray icon, I suspect Panel's Status Notifier plugin.

There's nothing wrong about the icon *in this code or in Telegrams's code* (I checked Telegrams's source) — the "workaround" I added here seems redundant (but it's harmless).

**Comment by stefonarch** [comment]
It happened again, after suspending  for a long time (~4h), same behavior. A short suspend doesn't trigger it.
With telegram or others no issue atm, could try those other apps where this issue was seen with,

**Comment by tsujan** [comment]
I checked the code of Status Notifier and found no issue in it either. We might need reports by different users to compare them.

If you want to test with other apps, you'll need to find those, whose tray icons have emblems. Telegram is such an app (with unread messages); I'm sure about that.

**Comment by stefonarch** [comment]
I think also meteo-qt is one of those.
![schermata-08-09-22-34](https://user-images.githubusercontent.com/10681413/128770824-df9d52cc-32dc-4cd4-a8d6-8ff5c2389a14.png)

Will report, until now it didn't happen again.

**Comment by tsujan** [comment]
> I think also meteo-qt is one of those.

I'm not sure — not comfortable with python+Qt codes — but it may be.

Could you please be more specific about what you see? Are you saying that the icon+emblem is there, then you suspend the computer and, after resuming, the icon is changed to the generic icon?

**Comment by stefonarch** [comment]
> Are you saying that the icon+emblem is there, then you suspend the computer and, after resuming, the icon is changed to the generic icon?

Exactly, this was twice the case now.

**Comment by tsujan** [comment]
> Exactly, this was twice the case now.

Oh, that's different from what I thought and a lot stranger! Thanks! I didn't think icons could change after resuming from suspend — and I've never seen it. Have no idea how it's possible.

**Comment by tsujan** [comment]
I think I've found a weird way of reproducing it on my old machine. It isn't related to resuming from suspend. Keeping my finger crossed, I hope it'll be still reproducible when I find the time to investigate it.

**Comment by stefonarch** [comment]
Well, nice! I rebooted yesterday and didn't see it again for now.

**Comment by tsujan** [comment]
I found a little time to investigate it. Fortunately, it's 100% reproducible with a sequence of actions.

Most probably, the cause of this weird problem is deep inside Qt. It only happens with hiding and showing the tray icon. I'd encountered a similar problem years ago (about not showing the tray menu). The workaround is elementary but I prefer to get nearer to its root before adding a commit to the PR. That may need more time.

**Comment by tsujan** [comment]
OK, done!

A short explanation:

`QSystemTrayIcon` definitely has a bug (under X11, at least), which shows up when the tray icon isn't a theme icon (like the emblemized icon I used): as soon as the tray icon is hidden, the non-theme icon is lost. The workaround I had in mind was re-adding it before the tray icon was shown, and it worked. However, because of another nasty problem in `QSystemTrayIcon`, there was a small memory leak. Also, removing and recreating the tray icon caused the same memory leak.

Since I hate memory leaks even when they're small, I removed the emblem and used the icon "notifications-disabled" for the do-not-disturb mode. If it doesn't exist in a theme, the usual icon ("preferences-desktop-notification") will be used. In this way, the code is simplified too.

NOTE: The above-mentioned bug doesn't happen with the power manager's emblem ("Pause idleness checks") because its tray icon is either shown or removed — we never hide it.

**Comment by stefonarch** [comment]
Testing, looks like that now, I like the do-not-disturb icon more now
![schermata-08-11-08-14](https://user-images.githubusercontent.com/10681413/128978944-49760995-59ec-4a62-a14a-efa982d79c68.png)
, but shouldn't be both the same (the bell)?
Could be confusing a little.

![schermata-08-11-08-11](https://user-images.githubusercontent.com/10681413/128978629-6c524bb0-1b39-481c-bd23-ed12b13cf420.png)

**Comment by tsujan** [comment]
> but shouldn't be both the same (the bell)?

You mean using "notifications" for the usual mode? I had the same idea but saw that "notifications" didn't exist in GTK icon themes.

Maybe we can use "notifications" and go to "preferences-desktop-notification" only if it doesn't exist.

**Comment by tsujan** [comment]
Added a commit to the PR for the last idea. You're right; the usual and no-disturb modes are more consistent with those icons.

If someone uses a GTK icon set, he'll only see "preferences-desktop-notification" but we know that GTK icon sets aren't good for Qt DEs in general.

**Comment by jmfernandez** [comment]
> Added a commit to the PR for the last idea. You're right; the usual and no-disturb modes are more consistent with those icons.
> 
> If someone uses a GTK icon set, he'll only see "preferences-desktop-notification" but we know that GTK icon sets aren't good for Qt DEs in general.

Maybe my current question is very off-topic. Something very useful in gtk-3.0 is that it is possible to set up a fallback icon theme where the toolkit looks for icons, in case the main icon theme does not have some icon for any reason. Does LXQt (or Qt itself) have something similar?

Your work providing an alternate icon name in case first icon name is not found is another way, assuring a decent fallback.

**Comment by tsujan** [comment]
> Does LXQt (or Qt itself) have something similar?

Yes, of course. LXQt follows freedesktop standards and looks for "dash fallbacks". If no icon is found, the generic icon will be used.

In addition to that, each app can decide which icon to use when a specific icon isn't found.
