### ISSUE TITLE
Visual artefact in notification popup

### ISSUE THREAD

**Issue by stefonarch** [lxqt/lxqt-notificationd#296]
I noticed it by setting spacing to a higher value (20), without a compositor it is black, with compositor transparent.

![schermata-12-17-19-02](https://user-images.githubusercontent.com/10681413/146588752-d2cc5d2d-b2a6-4821-9a2a-ecf4ede22aee.png)

![schermata-12-17-19-15-01](https://user-images.githubusercontent.com/10681413/146589713-b17c6e59-cdf7-4dd1-ae11-77daa394007a.png)

##### Steps to Reproduce (for bugs)

1. Select a theme with bright  notification popup (silver, kde-plasma)
2. set "spacing" in notification settings to 30
3. execute `notify-send test test`

##### Context

I saw that I was unable to click nearby under the  notification window.
##### System Information

* Distribution & Version:  arch/ manjaro with latest git; manjaro VM with LXQt 1.0.0
```
pacman -Qi lxqt-notificationd
Nome                      : lxqt-notificationd
Versione                  : 1.0.0-1
```

**Comment by tsujan** [comment]
That's expected. It *is* transparent but window transparency makes sense only with a compositor.

**Comment by stefonarch** [comment]
In 0.17 the window had no black upper and lower bars.

**Comment by tsujan** [comment]
Most probably because the spacing was 0. We haven't changed anything in that regard.

**Comment by stefonarch** [comment]
Lubuntu VM, kde-plasma, spacing 50:

![schermata-12-17-20-42](https://user-images.githubusercontent.com/10681413/146599834-5a1741f5-263a-4b10-8ca7-78991f0b2307.png)

Same with manjaro git:

![schermata-12-17-20-47-02](https://user-images.githubusercontent.com/10681413/146599910-48e0650e-13fe-44ea-af70-631eb432634a.png)


It wasn't there first, but I've no idea either where this could originate from. We didn't touch lxqt-notificationd.qss files.

Fact is that it depends on spacing, it likely adds a space from the border and one from the window, but only on top and bottom.

**Comment by tsujan** [comment]
> It wasn't there first, but I've no idea either where this could originate from

They may ship a distro config file with a big value for `spacing`.

Long story short, the notifications are widgets inside a parent widget. The latter is translucent and `spacing` sets its layout spacing. Nothing has changed in that regard and all your screenshots are correct. The black background you see in the screenshots without compositing are from the parent widget.

**Comment by tsujan** [comment]
> Lubuntu VM, kde-plasma, spacing 50, no compositor:

The virtual machine may have a kind of compositing.

**Comment by stefonarch** [comment]
Ok, my fault, sorry for the noise, I had not openbox without compton running but xfwm4 with compositing enabled in Lubuntu, disabling it those nice black bars appear too ;)

I started to see them lately because picom has very detailed settings and opacity for notification windows has to be set to "1" .

![schermata-12-17-21-24](https://user-images.githubusercontent.com/10681413/146603680-40c96e16-96cd-4f0c-add6-e836adf01a1d.png)

Only thing is that the "spacing" value actually get's doubled from top or bottom.

**Comment by tsujan** [comment]
I've had another kind of trouble with that spacing with KWin blur effect and Kvantum: If the spacing has a non-zero value, the empty space will be blurred too, which is ugly. The reason is that KWin's blur effect doesn't work based on the degree of translucency (100% for the empty space). So, I set it to zero.

On the other hand, Compiz's blurring works based on the degree of translucency and that spacing isn't a problem with it.

Of course, there's no issue without blurring.

The removal of the parent widget would need a complete rewrite of notifications GUI. I don't think there's another way but I might look into it if I find enough time.

**Comment by stefonarch** [comment]
In the mean time I noticed that those settings in picom doesn't have effect, it's always some border visible. 0 spacing is ugly too. 
I see that compton hasn't  had that issue, the container is completely invisible always as it is with compositing from xfwm4.

**Comment by tsujan** [comment]
> EDIT: only completely disable shadows it get's ok again. Picom bug I'say,

I think you could keep shadows for all windows and only disable them for `lxqt-notificationd`. If it has a shadow, the parent widget will have it, not the individual notification widgets and, since the parent is transparent, it'll look weird. So, I don't think it's a bug in Picom.

The same problem exists with KWin and Compiz. With them, I prefer to keep the shadow and set `spacing` to `0`:

![notifications](https://user-images.githubusercontent.com/981076/146615760-32fbc8d8-3245-4858-b0aa-7ca71572e74b.png)

**Comment by stefonarch** [comment]
Playing around I see it's not a problem of the shadow:

**Comment by tsujan** [comment]
> the problem is that picom not applies any setting for this WM type

Doesn't Picom accept names instead of types?

**Comment by stefonarch** [comment]
No idea, and lost enough time ;) 
Anyway, it paints the container borders and background, while compton didn't and xfwm doesn't too.

Could this parent widget vibility be an issue on wayland too?

**Comment by tsujan** [comment]
> Could this parent widget vibility be an issue on wayland too?

It isn't related to X11 or Wayland but to the WM/compositor, which draws the shadow. So, yes.

But don't worry about Wayland; it even doesn't allow us to put the notification at a specific position. If Wayland was usable in its current state, we would have LXQt-Wayland by now.

**Comment by stefonarch** [comment]
I don't care much about wayland, but it looks like fedora/gnome is using it as default, but I never looked at it.
Atm I switched to the xfwm4 compositor, but I'm missing "darken inactive windows"...

**Comment by tsujan** [comment]
To  support Wayland, each DE needs to have its own Wayland compositor+WM and directly "talk" to it for trivial jobs like window positioning. At some point, Wayland Kwin or KWinFT might be usable under an LXQt session and KF6/7/... might allow us to position panel, runner, notifications, etc., to have task manager icons,... — in short, to have tools for doing elementary jobs. Then, other jobs will still remain, and if we do all of them, we should say goodbye to both WM agnosticism and modularity (for example, our panel won't be usable under other DEs).

Who's motivated to go in that direction, I don't know. Personally, I prefer to naively hope that Wayland's mess will be fixed in future.
